title: "Variability Testing of Software Product Line: A Preference-based Dimensionality Reduction Approach"
description: Thiago do N. Ferreira, Silvia Regina Vergilio and Marouane Kessentini
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
